slurmstepd: info: Setting TMPDIR to /scratch/10942665. Previous errors about TMPDIR can be discarded
Slurm job started at 12/03/2025_02:39:00 PM

In transit.
Initing Ray (1 head node + 8 worker nodes + 8 simulation nodes) on nodes: 
	ilk-146 ilk-151 ilk-153 ilk-154 ilk-155 ilk-156 ilk-170 ilk-183 ilk-241 ilk-242 ilk-243 ilk-244 ilk-245 ilk-246 ilk-247 ilk-249 ilk-253
Head node: 172.30.204.2:6379


RAY_DEPLOY_TIME:     24.63628
2025-03-12 14:39:28,902	INFO packaging.py:520 -- Creating a file package for local directory '/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E6/DASK_ON_REISA/reduction/P16-SN8-LS536-GS8589-I20-AN8-D2025-03-12_10-04-02'.
2025-03-12 14:39:28,929	INFO packaging.py:347 -- Pushing file package 'gcs://_ray_pkg_7b30c20c4bf9e340.zip' (0.48MiB) to Ray cluster...
2025-03-12 14:39:28,936	INFO packaging.py:360 -- Successfully pushed file package 'gcs://_ray_pkg_7b30c20c4bf9e340.zip'.
RAY_INIT_TIME:       4.57262
Iter [0]
[2m[36m(iter_task pid=332352, ip=10.120.204.10)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=332352, ip=10.120.204.10)[0m   warnings.warn(
[2m[36m(iter_task pid=332351, ip=10.120.204.10)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=332351, ip=10.120.204.10)[0m   warnings.warn(
[2m[36m(iter_task pid=332350, ip=10.120.204.10)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=332350, ip=10.120.204.10)[0m   warnings.warn(
[2m[36m(iter_task pid=1207935, ip=10.120.204.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1207935, ip=10.120.204.26)[0m   warnings.warn(
[2m[36m(iter_task pid=1207932, ip=10.120.204.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1207932, ip=10.120.204.26)[0m   warnings.warn(
[2m[36m(iter_task pid=1207931, ip=10.120.204.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1207931, ip=10.120.204.26)[0m   warnings.warn(
[2m[36m(iter_task pid=1207934, ip=10.120.204.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1207934, ip=10.120.204.26)[0m   warnings.warn(
[2m[36m(iter_task pid=1207933, ip=10.120.204.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1207933, ip=10.120.204.26)[0m   warnings.warn(
[2m[36m(iter_task pid=1207936, ip=10.120.204.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1207936, ip=10.120.204.26)[0m   warnings.warn(
[2m[36m(iter_task pid=1840994, ip=10.120.204.9)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1840994, ip=10.120.204.9)[0m   warnings.warn(
[2m[36m(iter_task pid=1840992, ip=10.120.204.9)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1840992, ip=10.120.204.9)[0m   warnings.warn(
[2m[36m(iter_task pid=1840997, ip=10.120.204.9)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1840997, ip=10.120.204.9)[0m   warnings.warn(
[2m[36m(iter_task pid=1840995, ip=10.120.204.9)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1840995, ip=10.120.204.9)[0m   warnings.warn(
[2m[36m(iter_task pid=1840999, ip=10.120.204.9)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1840999, ip=10.120.204.9)[0m   warnings.warn(
[2m[36m(iter_task pid=1840996, ip=10.120.204.9)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1840996, ip=10.120.204.9)[0m   warnings.warn(
[2m[36m(iter_task pid=1840998, ip=10.120.204.9)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1840998, ip=10.120.204.9)[0m   warnings.warn(
[2m[36m(iter_task pid=1840993, ip=10.120.204.9)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1840993, ip=10.120.204.9)[0m   warnings.warn(
[2m[36m(iter_task pid=1841000, ip=10.120.204.9)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1841000, ip=10.120.204.9)[0m   warnings.warn(
[2m[36m(iter_task pid=1208011, ip=10.120.204.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1208011, ip=10.120.204.26)[0m   warnings.warn(
[2m[36m(iter_task pid=1208073, ip=10.120.204.26)[0m /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/dask/config.py:693: UserWarning: Configuration key "shuffle" has been deprecated. Please use "dataframe.shuffle.algorithm" instead
[2m[36m(iter_task pid=1208073, ip=10.120.204.26)[0m   warnings.warn(
Iter [2]
Iter [4]
Iter [6]
Iter [8]
Iter [10]
Iter [12]
Iter [14]
Iter [16]
The node with node id: 79f20430edf04a0c8641a92641a8fa801baabb48515a46dae9a58b4b and address: 172.30.211.15 and node name: 172.30.211.15 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
	(2) raylet has lagging heartbeats due to slow network or busy workload.
EST_ANALYTICS_TIME:  621.03742 (avg:31.05187)
Traceback (most recent call last):
  File "/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E6/DASK_ON_REISA/reduction/P16-SN8-LS536-GS8589-I20-AN8-D2025-03-12_10-04-02/reduction.py", line 56, in <module>
    result = handler.get_result(process_func, iter_func, selected_iters=iterations, kept_iters=max_iterations,
  File "/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E6/DASK_ON_REISA/reduction/P16-SN8-LS536-GS8589-I20-AN8-D2025-03-12_10-04-02/reisa.py", line 127, in get_result
    tmp = ray.get(results)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/worker.py", line 434, in get
    res = self._get(to_get, op_timeout)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/worker.py", line 462, in _get
    raise err
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/util/client/server/server.py", line 489, in _get_object
    items = ray.get(objectrefs, timeout=request.timeout)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/worker.py", line 2521, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: [36mray::iter_task()[39m (pid=1840998, ip=172.30.204.9)
  File "/mnt/lustre/scratch/nlsas/home/ulc/cursos/curso341/dask_on_reisa_tests/E6/DASK_ON_REISA/reduction/P16-SN8-LS536-GS8589-I20-AN8-D2025-03-12_10-04-02/reisa.py", line 113, in iter_task
    current_results = ray.get(current_results)  # type: #List[List[ray._raylet.ObjectRef]]
ray.exceptions.ActorUnschedulableError: The actor is not schedulable: The node specified via NodeAffinitySchedulingStrategy doesn't exist any more or is infeasible, and soft=False was specified.
srun: error: ilk-151: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=10942665.18
[14:49:58][MPI 000012][PyCall] *** error: while calling python, caught exception: ActorUnschedulableError: The actor is not schedulable: The node specified via NodeAffinitySchedulingStrategy doesn't exist any more or is infeasible, and soft=False was specified.

At:
  /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/worker.py(2542): get
  /home/ulc/cursos/curso341/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py(105): wrapper
  <string>(38): <module>

srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 10942665 ON ilk-146 CANCELLED AT 2025-03-12T14:59:20 DUE TO TIME LIMIT ***
*** SIGTERM received at time=1741787960 on cpu 16 ***
slurmstepd: error: *** STEP 10942665.19 ON ilk-242 CANCELLED AT 2025-03-12T14:59:20 DUE TO TIME LIMIT ***
*** SIGTERM received at time=1741787960 on cpu 24 ***
*** SIGTERM received at time=1741787960 on cpu 49 ***
*** SIGTERM received at time=1741787960 on cpu 27 ***
*** SIGTERM received at time=1741787960 on cpu 0 ***
*** SIGTERM received at time=1741787960 on cpu 20 ***
*** SIGTERM received at time=1741787960 on cpu 0 ***
*** SIGTERM received at time=1741787960 on cpu 63 ***
*** SIGTERM received at time=1741787960 on cpu 0 ***
[failure_signal_handler.cc : 329] RAW: Signal 15 raised at PC=0x149c25d11d05 while already in AbslFailureSignalHandler()
*** SIGTERM received at time=1741787960 on cpu 24 ***
[failure_signal_handler.cc : 329] RAW: Signal 15 raised at PC=0x1535a517d54c while already in AbslFailureSignalHandler()
*** SIGTERM received at time=1741787960 on cpu 49 ***
*** SIGTERM received at time=1741787960 on cpu 15 ***
[failure_signal_handler.cc : 329] RAW: Signal 15 raised at PC=0x14b874a302f4 while already in AbslFailureSignalHandler()
*** SIGTERM received at time=1741787960 on cpu 63 ***
[failure_signal_handler.cc : 329] RAW: Signal 15 raised at PC=0x14c0b3eba2f4 while already in AbslFailureSignalHandler()
*** SIGTERM received at time=1741787960 on cpu 23 ***
PC: @     0x1535a517d54c  (unknown)  __read
    @     0x1535a50c19c0       3456  (unknown)
PC: @     0x14c0b3eba2f4  (unknown)  __open
PC: @     0x14b874a302f4  (unknown)  __open
    @     0x14c0b3dfe9c0  (unknown)  (unknown)
    @     0x14b8749749c0  (unknown)  (unknown)
